camera:
  backend: "opencv"
  secrets_file: "secrets/camera_secrets.yaml"
  resolution: [1280, 720]
  fps: 30
  swap_rb: false
  rotate: 0
  flip_horizontal: false
  flip_vertical: false
detection:
  backend: "yolo"
  yolo:
    model: "yolov8s.pt"
    conf_threshold: 0.35
    classes: [0, 1, 2, 3, 5, 7]
    class_name_overrides:
      0: "person"
      1: "bicycle"
      2: "car"
      3: "motorcycle"
      5: "bus"
      7: "truck"
counting:
  mode: "gate"
  line_a:
  - - 0.5710332103321033
    - 0.26404264042640424
  - - 0.3422509225092251
    - 0.8265682656826568
  line_b:
  - - 0.6162361623616236
    - 0.3132431324313243
  - - 0.44003690036900367
    - 0.8724887248872488
  direction_labels:
    a_to_b: southbound
    b_to_a: northbound
